### PR TITLE
Display correct number of critical updates in apt plugin output

### PR DESCRIPTION
**Pull request by jcharaoui**
This commit improves the apt check_mk plugin output by displaying the true number of critical and normal updates in the status message.

### CODE REVIEW

**Comment by lgbff** [comment]
sorry, i have not enoth freetime to fix this....
pls wait ;-)

**Comment by lgbff** [comment]
pls don't mix several merge request on one topic, thx.

**Comment by jcharaoui** [comment]
I'm aware of the caching mechanism, however this requires a relatively recent version of Check_MK which isn't available in my environment yet.

**Comment by lgbff** [comment]
Sorry, the cache modus is available in actual stable version 1.2.6.
I'dont patch the agent for older versions, i cant test it.
thx for understanding.

**Comment by jcharaoui** [comment]
That's fine.

**Comment by lgbff** [comment]
complete with 636761a3dd873b71a197b91781ac00ceb979fa16

**Pull request closed without merging**
